#!/bin/bash
case $BLOCK_BUTTON in
		1) sp play ;; # left click
		4) sp next ;; # scroll up
		5) sp prev ;; # scroll down
esac

if sp status | grep 'Paused' > /dev/null; then
	printf '\xef\x81\x8c ' # fa-pause
else
	printf '\xef\x81\x8b ' # fa-play
fi
sp current-oneline
#dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | awk 'BEGIN {RS=" entry\\("; FS="\""}; /artist/ {artist = $4}; /title/ {title = $4} END { print artist": "title}'
#exit 0
